/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import BusinessLogic.Staff;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicky
 */
public class ManageUsers extends javax.swing.JFrame
{

    /**
     * Creates new form ManageUsers
     */
    public ManageUsers()
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnRegisterUser = new javax.swing.JButton();
        btnAddUser = new javax.swing.JButton();
        btnUnregisterUser = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 500));
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowActivated(java.awt.event.WindowEvent evt)
            {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "Name", "Surname", "Cell No", "Email", "Department", "*"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tblStaff.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblStaff);
        if (tblStaff.getColumnModel().getColumnCount() > 0)
        {
            tblStaff.getColumnModel().getColumn(0).setMinWidth(110);
            tblStaff.getColumnModel().getColumn(0).setMaxWidth(110);
            tblStaff.getColumnModel().getColumn(1).setMinWidth(70);
            tblStaff.getColumnModel().getColumn(1).setMaxWidth(70);
            tblStaff.getColumnModel().getColumn(2).setMinWidth(70);
            tblStaff.getColumnModel().getColumn(2).setMaxWidth(70);
            tblStaff.getColumnModel().getColumn(4).setMinWidth(110);
            tblStaff.getColumnModel().getColumn(4).setMaxWidth(110);
            tblStaff.getColumnModel().getColumn(5).setMinWidth(110);
            tblStaff.getColumnModel().getColumn(5).setMaxWidth(110);
            tblStaff.getColumnModel().getColumn(6).setMinWidth(25);
            tblStaff.getColumnModel().getColumn(6).setMaxWidth(25);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 70, 600, 320);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("MANAGE USERS");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 20, 190, 29);

        btnBack.setText("BACK");
        btnBack.setName("btnBack"); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(530, 20, 90, 30);

        btnRegisterUser.setText("✓");
        btnRegisterUser.setName("btnRegisterUser"); // NOI18N
        btnRegisterUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegisterUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegisterUser);
        btnRegisterUser.setBounds(570, 400, 50, 35);

        btnAddUser.setText("ADD USER");
        btnAddUser.setName("btnAddUser"); // NOI18N
        btnAddUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddUser);
        btnAddUser.setBounds(250, 400, 141, 35);

        btnUnregisterUser.setText("X");
        btnUnregisterUser.setName("btnUnregisterUser"); // NOI18N
        btnUnregisterUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnUnregisterUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnregisterUser);
        btnUnregisterUser.setBounds(510, 400, 50, 35);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG.jpg"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 650, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBackActionPerformed
    {//GEN-HEADEREND:event_btnBackActionPerformed
        AdminMain frame = new AdminMain();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegisterUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegisterUserActionPerformed
    {//GEN-HEADEREND:event_btnRegisterUserActionPerformed
        if (tblStaff.getSelectedRow() >= 0)
        {
            if (tblStaff.getValueAt(tblStaff.getSelectedRow(), 6).equals(false))
            {
                try
                {
                    if (JOptionPane.showConfirmDialog(null, "Are you sure you want to register " + tblStaff.getValueAt(tblStaff.getSelectedRow(), 1) + "?") == JOptionPane.OK_OPTION)
                    {
                        Staff.RegisterStaff((String) tblStaff.getValueAt(tblStaff.getSelectedRow(), 0));
                    }
                } catch (ClassNotFoundException ex)
                {
                    Logger.getLogger(ManageUsers.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex)
                {
                    Logger.getLogger(ManageUsers.class.getName()).log(Level.SEVERE, null, ex);
                } finally
                {
                    SetTableValues();
                }
            } else
            {
                JOptionPane.showMessageDialog(null, "This staff member has already been registered!");
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "Select a staff member!");
        }
    }//GEN-LAST:event_btnRegisterUserActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowActivated
    {//GEN-HEADEREND:event_formWindowActivated
        SetTableValues();
    }//GEN-LAST:event_formWindowActivated

    public void SetTableValues()
    {
        try
        {
            List<Staff> staff = Staff.GetStaffFromDatabase();

            DefaultTableModel model = (DefaultTableModel) tblStaff.getModel();
            model.setRowCount(0);

            Object rowData[] = new Object[7];

            for (int i = 0; i < staff.size(); i++)
            {
                rowData[0] = staff.get(i).getId();
                rowData[1] = staff.get(i).getName();
                rowData[2] = staff.get(i).getSurname();
                rowData[3] = staff.get(i).getCellNo();
                rowData[4] = staff.get(i).getEmail();
                rowData[5] = staff.get(i).getDepartment().getDescription();
                rowData[6] = staff.get(i).getLogin().isRegistered();
                model.addRow(rowData);
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(ManageUsers.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex)
        {
            Logger.getLogger(ManageUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddUserActionPerformed
    {//GEN-HEADEREND:event_btnAddUserActionPerformed
        AddUser frame = new AddUser();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnUnregisterUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnUnregisterUserActionPerformed
    {//GEN-HEADEREND:event_btnUnregisterUserActionPerformed
        if (tblStaff.getSelectedRow() >= 0)
        {
            if (tblStaff.getValueAt(tblStaff.getSelectedRow(), 6).equals(true))
            {
                try
                {
                    if (JOptionPane.showConfirmDialog(null, "Are you sure you want to unregister " + tblStaff.getValueAt(tblStaff.getSelectedRow(), 1) + "?") == JOptionPane.OK_OPTION)
                    {
                        Staff.UnregisterStaff((String) tblStaff.getValueAt(tblStaff.getSelectedRow(), 0));
                    }
                } catch (ClassNotFoundException ex)
                {
                    Logger.getLogger(ManageUsers.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex)
                {
                    Logger.getLogger(ManageUsers.class.getName()).log(Level.SEVERE, null, ex);
                } finally
                {
                    SetTableValues();
                }
            } else
            {
                JOptionPane.showMessageDialog(null, "This staff member is not registered!");
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "Select a staff member!");
        }
    }//GEN-LAST:event_btnUnregisterUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ManageUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegisterUser;
    private javax.swing.JButton btnUnregisterUser;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStaff;
    // End of variables declaration//GEN-END:variables
}
